# Generated by Django 2.0.3 on 2018-05-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('team_size', models.IntegerField(max_length=10)),
                ('duration', models.IntegerField(max_length=10)),
                ('response_day', models.IntegerField(max_length=10)),
                ('budget', models.FloatField()),
                ('revenue_plan', models.FloatField()),
                ('target_revenue', models.FloatField()),
                ('additional_cost', models.FloatField()),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('details', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='uploads/200/default.png', upload_to='uploads/200/')),
                ('is_active', models.BooleanField(default=True)),
                ('activation_code', models.CharField(max_length=50)),
                ('password_reset_code', models.CharField(default=0, max_length=50)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Role')),
            ],
        ),
        migrations.AddField(
            model_name='projecttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by+', to='users.User'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by+', to='users.User'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by+', to='users.User'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by+', to='users.User'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ProjectInfo'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by+', to='users.User'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by+', to='users.User'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ProjectType'),
        ),
    ]
