# Generated by Django 2.0.1 on 2018-05-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180517_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='response_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='team_size',
            field=models.IntegerField(),
        ),
    ]
